# Generated by Django 4.2 on 2026-06-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('product_type', models.CharField(choices=[('health', 'Health Insurance'), ('term', 'Term Insurance'), ('policy_review', 'Policy Review')], max_length=20)),
                ('appointment_date', models.DateTimeField()),
                ('appointment_slot', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_type', models.CharField(default='NEW', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custID', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('repeat_count', models.PositiveIntegerField(default=1)),
                ('dateOfRegistration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
