# Generated by Django 4.2 on 2026-03-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('insurance_type', models.CharField(choices=[('self', 'Self'), ('corporate', 'Corporate')], max_length=20)),
                ('product_type', models.CharField(choices=[('health', 'Health Insurance'), ('term', 'Term Insurance')], max_length=20)),
                ('appointment_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
