# Generated by Django 4.2 on 2026-04-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='insurance_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
    ]
