# Generated by Django 4.2 on 2026-04-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='repeat_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
