# Generated by Django 4.2 on 2026-04-05 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_alter_customer_repeat_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer_type',
            field=models.CharField(default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='dateOfRegistration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
