# Generated by Django 4.2 on 2026-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_appointment_customer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
