# Generated by Django 4.2 on 2026-04-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_appointment_appointment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custID',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
